# Generated by Django 3.1.7 on 2021-03-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileAPI',
        ),
    ]
