# Generated by Django 3.1.7 on 2021-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20201208_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.BigIntegerField(default=0, verbose_name='积分'),
        ),
    ]
